name: Github actions learning
'on':
  push:
    branches:
      - main
jobs:
  demo: null
  runs-on: ubuntu-latest
  steps: null
  name: Git workflow running
  run: echo "Github workflow is running successfully"
