name: Manual workflow test
#name of the workflow
on:
  workflow_dispatch:
    inputs:
     Buildenv:
       description: "Select the build environment eg: dev, staging, prod"
       required: true
       type: string


jobs:
  Worflow_test:
    runs-on: ubuntu-latest
    steps:
      - name: Git workflow running
        run: echo ${{inputs.Buildenv}}

      - name: Workflow test
        run: echo "Github workflow is running successfully"
      
      - name: YML instructions working 
        run: echo "YML instructions are used to create workflow in github actions"
